wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711361180.374632
    t:
      1:
      - 1
      - 50
      - 55
      - 77
      2:
      - 1
      - 50
      - 55
      - 77
      3:
      - 2
      - 13
      - 14
      - 23
      4: 3.11.0
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
experiment_config:
  desc: null
  value:
    sampling_device: cpu
    train_device: cpu
    share_policy_params: true
    prefer_continuous_actions: true
    gamma: 0.9
    lr: 5.0e-05
    adam_eps: 1.0e-06
    clip_grad_norm: true
    clip_grad_val: 5
    soft_target_update: true
    polyak_tau: 0.005
    hard_target_update_frequency: 5
    exploration_eps_init: 0.8
    exploration_eps_end: 0.01
    exploration_anneal_frames: null
    max_n_iters: 1000
    max_n_frames: null
    on_policy_collected_frames_per_batch: 6000
    on_policy_n_envs_per_worker: 10
    on_policy_n_minibatch_iters: 45
    on_policy_minibatch_size: 400
    off_policy_collected_frames_per_batch: 6000
    off_policy_n_envs_per_worker: 10
    off_policy_n_optimizer_steps: 1000
    off_policy_train_batch_size: 128
    off_policy_memory_size: 1000000
    off_policy_init_random_frames: 0
    evaluation: true
    render: true
    evaluation_interval: 120000
    evaluation_episodes: 10
    evaluation_deterministic_actions: true
    loggers:
    - wandb
    create_json: true
    save_folder: null
    restore_file: null
    checkpoint_interval: 300000
algorithm_config:
  desc: null
  value:
    share_param_critic: false
    clip_epsilon: 0.2
    entropy_coef: 0.0
    critic_coef: 1.0
    loss_critic_type: l2
    lmbda: 0.9
    scale_mapping: biased_softplus_1.0
    use_tanh_normal: true
model_config:
  desc: null
  value:
    topology: full
    self_loops: false
    gnn_class: torch_geometric.nn.conv.gatv2_conv.GATv2Conv
    gnn_kwargs: {}
task_config:
  desc: null
  value:
    max_steps: 200
    n_agents: 2
    n_goals: 2
    final_reward: 0.01
    pos_shaping: true
continuous_actions:
  desc: null
  value: true
on_policy:
  desc: null
  value: true
algorithm_name:
  desc: null
  value: mappo
model_name:
  desc: null
  value: gnn
task_name:
  desc: null
  value: painting
environment_name:
  desc: null
  value: vmas
seed:
  desc: null
  value: 0
